mariaDB4j:
  port: 3307

server:
  port: 8080

spring:
  profiles: local
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3307/spring?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  logging:
    level:
      org.hibernate.SQL: DEBUG
  flyway:
    enabled: true
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3307/spring?useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
  data:
    redis:
      repositories:
        enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

cache:
  redis:
    enabled: false
    host: localhost
    port: 6379
    timeout: 120ms
    custom:
      socket:
        timeout: 400ms