spring:
  profiles: prod
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/spring?useUnicode=true&characterEncoding=UTF-8
    username: base
    password: ZaQBRLswyt!TmCmJtGhyC
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
  logging:
    level:
      org.hibernate.SQL: DEBUG
  flyway:
    enabled: true
    url: jdbc:mariadb://127.0.0.1:3306/spring?useUnicode=true&characterEncoding=UTF-8
  data:
    redis:
      repositories:
        enabled: false

server:
  port: 80