server:
  port: 80

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring?useUnicode=true&characterEncoding=UTF-8
    username: base
    password: ZaQBRLswyt!TmCmJtGhyC
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
  logging:
    level:
      org.hibernate.SQL: DEBUG
  flyway:
    enabled: true
    url: jdbc:mysql://127.0.0.1:3306/spring?useUnicode=true&characterEncoding=UTF-8
    username: base
    password: ZaQBRLswyt!TmCmJtGhyC
  data:
    redis:
      repositories:
        enabled: false

cache:
  redis:
    enabled: true
    host: localhost
    port: 6379
    timeout: 120ms
    custom:
      socket:
        timeout: 400ms